#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

// Docs/07 §17 — 팀 공유 자동화 파이프라인.
// 팀원이 git pull 후 Unity를 열면 자동으로 다음을 일괄 실행해 모두가 같은 씬 상태를 보게 한다.
//   1) MR_Player FBX 재임포트(Avatar 정합)
//   2) MR_Player.controller 빌드
//   3) Prototype3D 씬에 MR_Player_Model 부착 + 와이어링
//   4) Collision & Overlap Pass (콜라이더 보강 + 겹침 해소 + 카메라 마스크)
//   5) Proposal Map Composition Pass (기획서 기반 구역 배치/상징 프롭)
//   6) Prototype3D.unity 저장
// 적용 결과는 setup version 파일(SetupVersion.txt)에 기록하고, 버전이 다를 때만 재실행한다.
[InitializeOnLoad]
public static class MR_FullSetupPipeline
{
    // 파이프라인 구성/순서가 바뀔 때마다 이 상수를 올려주면 팀 전체가 다음 pull 후 한 번 더 자동 실행한다.
    public const string PipelineVersion = "2026.05.21.5";

    private const string SetupVersionAssetPath = "Assets/MemoryRecycler3D/SetupVersion.txt";
    private const string ScenePath = "Assets/MemoryRecycler3D/Scenes/Prototype3D.unity";
    private const string SessionRanKey = "MR3D_FullSetupPipeline_Ran_v1";

    static MR_FullSetupPipeline()
    {
        EditorApplication.delayCall += RunIfOutdated;
        EditorApplication.playModeStateChanged += OnPlayModeChanged;
    }

    private static void OnPlayModeChanged(PlayModeStateChange change)
    {
        if (change == PlayModeStateChange.ExitingEditMode)
        {
            // Play 진입 직전에는 한 번 더 확인 — 누군가 도중에 씬을 바꿔도 안전.
            if (IsLocalVersionOutdated())
                RunPipeline(force: false, reason: "PlayEnter");
        }
    }

    private static void RunIfOutdated()
    {
        if (SessionState.GetBool(SessionRanKey, false))
            return;
        if (!IsLocalVersionOutdated())
        {
            SessionState.SetBool(SessionRanKey, true);
            return;
        }
        RunPipeline(force: false, reason: "EditorLoad");
        SessionState.SetBool(SessionRanKey, true);
    }

    private static bool IsLocalVersionOutdated()
    {
        // 프로젝트 안의 SetupVersion.txt가 우리의 PipelineVersion과 다르면 outdated.
        // 팀원이 pull 받은 새 PipelineVersion 상수와 자기 워크스페이스의 SetupVersion.txt를 비교한다.
        string localVersion = ReadLocalVersion();
        return localVersion != PipelineVersion;
    }

    private static string ReadLocalVersion()
    {
        if (!File.Exists(SetupVersionAssetPath))
            return string.Empty;
        try
        {
            string raw = File.ReadAllText(SetupVersionAssetPath).Trim();
            // 파일 첫 줄만 버전으로 사용. 그 아래는 사람이 읽는 메타정보.
            int newline = raw.IndexOf('\n');
            return newline > 0 ? raw.Substring(0, newline).Trim() : raw;
        }
        catch
        {
            return string.Empty;
        }
    }

    private static void WriteLocalVersion()
    {
        string body =
            PipelineVersion + "\n" +
            "# Generated by MR_FullSetupPipeline\n" +
            "# 이 파일은 팀 공용 자동화 파이프라인의 적용 버전을 기록합니다.\n" +
            "# 수동으로 수정하지 마세요. 팀 전체에 새 자동화가 필요할 때는\n" +
            "# MR_FullSetupPipeline.PipelineVersion 상수를 올리고 커밋하세요.\n" +
            "# Last applied: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + "\n";

        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(SetupVersionAssetPath));
            File.WriteAllText(SetupVersionAssetPath, body);
            AssetDatabase.ImportAsset(SetupVersionAssetPath);
        }
        catch (Exception e)
        {
            Debug.LogWarning("[MR_FullSetupPipeline] SetupVersion.txt 쓰기 실패: " + e.Message);
        }
    }

    // ─── 통합 메뉴 ────────────────────────────────────────────────
    [MenuItem("Tools/Memory Recycler 3D/Apply Full Setup (Team)")]
    public static void ApplyFullSetupMenu()
    {
        RunPipeline(force: true, reason: "ManualMenu");
    }

    [MenuItem("Tools/Memory Recycler 3D/Show Setup Status")]
    public static void ShowSetupStatus()
    {
        string local = ReadLocalVersion();
        string msg =
            "현재 PipelineVersion : " + PipelineVersion + "\n" +
            "로컬 SetupVersion.txt : " + (string.IsNullOrEmpty(local) ? "(없음)" : local) + "\n" +
            "상태 : " + (IsLocalVersionOutdated() ? "재실행 필요" : "최신");
        EditorUtility.DisplayDialog("MR3D Setup Status", msg, "확인");
    }

    // ─── 파이프라인 본체 ──────────────────────────────────────────
    public static void RunPipeline(bool force, string reason)
    {
        if (EditorApplication.isCompiling || EditorApplication.isUpdating)
        {
            // 컴파일 중이면 다음 delayCall에 다시 시도.
            EditorApplication.delayCall += () => RunPipeline(force, reason);
            return;
        }

        if (Application.isPlaying)
        {
            Debug.LogWarning("[MR_FullSetupPipeline] Play 중에는 파이프라인을 실행하지 않습니다.");
            return;
        }

        try
        {
            AssetDatabase.StartAssetEditing();
            Debug.Log("[MR_FullSetupPipeline] 시작 (reason=" + reason + ", version=" + PipelineVersion + ")");

            // 1~3) MR_Player 셋업: 이미 외부 유틸이 멱등 동작하므로 그대로 호출.
            SafeStep("Player Setup", () => MR_PlayerAutoSetup.EnsurePlayerSetup(force));

            // 4) Collision & Overlap Pass
            SafeStep("Collision Pass", () => MR_CollisionOverlapPass.ApplyPass());

            // 5) 제안서 맵 구성 패스 — 기존 연결은 유지하고 구역감/상징 프롭만 비파괴 적용.
            SafeStep("Proposal Map Composition Pass", () => MR_ProposalMapCompositionPass.ApplyPass());

            // 6) 씬 저장
            Scene scene = GetOrOpenPrototype();
            if (scene.IsValid())
            {
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
            }

            // 6) 버전 도장
            WriteLocalVersion();

            Debug.Log("[MR_FullSetupPipeline] 완료 — 모든 팀원이 같은 씬 상태로 정렬됩니다.");
        }
        finally
        {
            AssetDatabase.StopAssetEditing();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }

    private static void SafeStep(string label, Action step)
    {
        try
        {
            step();
        }
        catch (Exception e)
        {
            // 한 단계가 실패해도 나머지 단계는 진행. 콘솔에 어느 단계인지 명시.
            Debug.LogError("[MR_FullSetupPipeline] " + label + " 실패: " + e);
        }
    }

    private static Scene GetOrOpenPrototype()
    {
        for (int i = 0; i < SceneManager.sceneCount; i++)
        {
            Scene s = SceneManager.GetSceneAt(i);
            if (s.path == ScenePath)
                return s;
        }
        if (!File.Exists(ScenePath))
            return default;
        return EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
    }
}
#endif
